host   = "127.0.0.1"
port   = 8000
logdir = "log"
title  = "Rustmark"

[local_loading]
html             = "Deny"
markdown         = "Supplement"
protected_assets = "Override"
public_assets    = "Override"

[local_paths]
html             = "html"
markdown         = "content"
protected_assets = "content"
public_assets    = "static"

[static_files]
stream_threshold = 1000
stream_buffer    = 256
read_buffer      = 128

[stats]
enabled                = true
timing_buffer_size     = 86_400 # One day: 60 * 60 * 24
connection_buffer_size = 86_400 # One day: 60 * 60 * 24
memory_buffer_size     = 86_400 # One day: 60 * 60 * 24
ws_ping_interval       = 60
ws_ping_timeout        = 10

[stats_periods]
second =      1
minute =     60
hour   =  3_600
day    = 86_400

[users]
#joe = "1a2b3c"
